### ISSUE TITLE
Low-level register map addresses 

### ISSUE THREAD

**Issue by aacuevas** [open-ephys/ONI#5]
Ported from https://github.com/jonnew/ONI/issues/6

Original text:
> **Register address spaces**
> Right now we have 11 specific registers and allow custom registers to exist past that, not giving space for future revisions. Proposed register space would be split three 4MByte (for 32-bit values) regions:
> 0x00000000-0x000FFFFF: Oni register space. Reserved for the specification registers and future additions to them
> 0x0010000-0x003FFFFF: Reserved for oni-spec compliance information 
> 0x00400000-0xFFFFFFFF: Device specific optional registers
> 
> The split is done this way to make it easier to develop for a wider range of hardware devices, as not all interfaces might have a full 32-bit address scheme available. 24-bit addressing is a common value, and this could cover all addresses on that space. It is unlikely that more than 20bit addressing per region will be required.

This will still allows for the custom options to exist, if required by hardware, without risking overlapping future spec revisions

**Comment by jonnew** [comment]
This a breaking change, but is obviously correct.  There should be four blocks with equal spans over a 16-bit address space:

1. Oni register space. Reserved for the specification registers and future additions to them (the above image)
2. Oni spec compliance
   - Information on ONI standard compliance (e.g. version)
   - Additionally parameterization that is required by the spec. For instance data boundary sizes, which can be different for different implementations, can be provided here.
   - Maximal size of the hardware buffer accepting data and maybe reading data
   - Maybe: optional features? indication that the hardware has or has not implemented them so that downstream can take advantage in its behavior.
3. Device specific optional registers
   - Out of spec registers that may be required by hardware in which the ONI compliance is a subset of their complete functionality
4. Reserved for future use. 


While we are at it, we should switch the positions of the register programming interface and global register positions:

![image](https://github.com/user-attachments/assets/d05d7228-0fc6-4ebd-b509-4fe0be13621a)

**Comment by jonnew** [comment]
@aacuevas suggest potentially increasing the Global registers subspace within region (1) to allow more global registers to be added. @jonnew is agnostic because Global vs. Register Interface are really just words in his opinion and its hard to account for the future.
